# Generated by Django 3.2 on 2022-10-19 12:27

import core.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('session_id', models.TextField()),
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('audio_recording', models.FileField(upload_to=core.models.upload_location_activity_images)),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.IntegerField(unique=True)),
                ('duration_in_sec', models.IntegerField(default=30)),
                ('no_question_to_display', models.IntegerField(default=1)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='record',
            name='voice_record',
            field=models.FileField(upload_to=core.models.upload_location_activity_images),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('question', models.TextField(unique=True)),
                ('display_question_on_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_questions', to='core.step')),
            ],
        ),
    ]
